spring:
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML5
  resources:
    static-locations:
      - classpath:/templates/
      - classpath:/static/
  h2:
    console:
      enabled: true


server:
  port: 9000

logging:
  level:
    root: info
    org.springframework.web: info